from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from pydantic import BaseModel, Field


class LogEntry(BaseModel):
    at: str
    action: str
    actor: str
    doc_ids: list[str] = Field(default_factory=list)
    note: str


class ScaffoldEntry(BaseModel):
    content: str
    cli_owned: bool


class InitResult(BaseModel):
    root: Path
    created: list[str] = Field(default_factory=list)
    overwritten: list[str] = Field(default_factory=list)
    skipped: list[str] = Field(default_factory=list)


def format_log_entry(entry: LogEntry) -> str:
    ids = ",".join(entry.doc_ids) if entry.doc_ids else "-"
    return f"- {entry.at} | {entry.action} | {entry.actor} | {ids} | {entry.note}"


def _utc_now() -> str:
    value = datetime.now(timezone.utc).replace(microsecond=0)
    return value.isoformat().replace("+00:00", "Z")


def _index(title: str, description: str, listing: str = "") -> str:
    content = (
        f"---\ntype: index\ndescription: {description}\n---\n"
        f"# {title}\n\n"
        "<!-- Generated by kb — do not edit; run `kb index` to regenerate. -->\n"
    )
    return content if not listing else f"{content}\n{listing}\n"


ROOT_LISTING = """## Subdirectories
* [Governance](governance/index.md) - Project governance — configuration, conventions, and templates.
* [Raw Evidence](raw/index.md) - Immutable evidence — sources, session records, and feedback.
* [Synthetic Documents](synthetic/index.md) - Human-created, agent-maintained documents (the derivation graph)."""

GOVERNANCE_LISTING = """## Subdirectories
* [Templates](templates/index.md) - Optional per-type document templates.

## Files
* [GOVERNANCE-CONVENTIONS][Project Conventions](conventions.md) - Standing conventions for this knowledge base. Human-maintained.
* [GOVERNANCE-KB-CONFIG][KB Configuration Reference](kb-config.md) - Explains each field in the root kb-config.json. Human-readable companion to the machine-read config."""

RAW_LISTING = """## Subdirectories
* [Session Records](chats/index.md) - Session records from kb-author and kb-ingest sessions (immutable).
* [Feedback](feedback/index.md) - Consumer feedback about synthetic documents (immutable).
* [Sources](sources/index.md) - Normalized external evidence (immutable)."""

CONFIG_CONTENT = """{
  "schema": 1,
  "types": [],
  "tags": [],
  "id_prefixes": {
    "synthetic": "KB",
    "source": "RAW",
    "chat": "CHAT",
    "feedback": "FEED"
  },
  "propagation_auto_safe": []
}
"""

CONVENTIONS_CONTENT = """---
id: GOVERNANCE-CONVENTIONS
type: conventions
title: Project Conventions
description: Standing conventions for this knowledge base. Human-maintained.
---
# Project Conventions

Standing conventions for this knowledge base. Human-maintained.

## Writing
(none yet)

## Structure
(none yet)
"""

CONFIG_REFERENCE_CONTENT = """---
id: GOVERNANCE-KB-CONFIG
type: kb-config
title: KB Configuration Reference
description: Explains each field in the root kb-config.json. Human-readable companion to the machine-read config.
---
# KB Configuration Reference

The project's configuration and root marker is `kb-config.json` at the KB root.
It is strict JSON, read directly by `kb` commands. Edit the fields below to suit
the project; `schema` is managed by `kb` — do not edit it.

## Fields

- **`schema`** — KB layout schema version. Reserved and tooling-owned; `kb`
  refuses a KB whose schema is newer than the CLI understands.
- **`types`** — document type vocabulary (open list). Examples: `outcome`,
  `ux-flow`, `coding-spec`, `test-plan`, `adr`, `runbook`, `context-package`.
  An empty list means types are not yet constrained.
- **`tags`** — tag vocabulary. `kb validate` flags any document tag not listed
  here. An empty list means no tags are declared.
- **`id_prefixes`** — the id prefix used per document class: `synthetic` (`KB`),
  `source` (`RAW`), `chat` (`CHAT`), `feedback` (`FEED`). Ids are `<PREFIX>-<6+ digits>`.
- **`propagation_auto_safe`** — change classes governance considers auto-safe
  during propagation (CS3). Start empty; expand from field data (PRD OQ1).
"""


def _log_content(timestamp: str) -> str:
    entry = format_log_entry(
        LogEntry(
            at=timestamp,
            action="initialized",
            actor="kb-cli",
            doc_ids=[],
            note="KB scaffolded by kb init",
        )
    )
    return (
        "---\ntype: log\n---\n"
        "<!-- KB history — append-only; written by `kb log`. Format: - <UTC ISO> | <action> | <actor> | <ids or -> | <note> -->\n"
        f"# Knowledge Base Log\n\n{entry}\n"
    )


def _manifest(timestamp: str) -> dict[str, ScaffoldEntry]:
    return {
        "governance/conventions.md": ScaffoldEntry(
            content=CONVENTIONS_CONTENT, cli_owned=False
        ),
        "governance/index.md": ScaffoldEntry(
            content=_index(
                "Governance",
                "Project governance — configuration, conventions, and templates.",
                GOVERNANCE_LISTING,
            ),
            cli_owned=True,
        ),
        "governance/kb-config.md": ScaffoldEntry(
            content=CONFIG_REFERENCE_CONTENT, cli_owned=False
        ),
        "governance/templates/index.md": ScaffoldEntry(
            content=_index("Templates", "Optional per-type document templates."),
            cli_owned=True,
        ),
        "index.md": ScaffoldEntry(
            content=_index(
                "Knowledge Base",
                "Root of the knowledge base — raw evidence, synthetic documents, and governance.",
                ROOT_LISTING,
            ),
            cli_owned=True,
        ),
        "kb-config.json": ScaffoldEntry(content=CONFIG_CONTENT, cli_owned=True),
        "log.md": ScaffoldEntry(content=_log_content(timestamp), cli_owned=False),
        "raw/chats/index.md": ScaffoldEntry(
            content=_index(
                "Session Records",
                "Session records from kb-author and kb-ingest sessions (immutable).",
            ),
            cli_owned=True,
        ),
        "raw/feedback/index.md": ScaffoldEntry(
            content=_index(
                "Feedback", "Consumer feedback about synthetic documents (immutable)."
            ),
            cli_owned=True,
        ),
        "raw/index.md": ScaffoldEntry(
            content=_index(
                "Raw Evidence",
                "Immutable evidence — sources, session records, and feedback.",
                RAW_LISTING,
            ),
            cli_owned=True,
        ),
        "raw/sources/index.md": ScaffoldEntry(
            content=_index("Sources", "Normalized external evidence (immutable)."),
            cli_owned=True,
        ),
        "synthetic/index.md": ScaffoldEntry(
            content=_index(
                "Synthetic Documents",
                "Human-created, agent-maintained documents (the derivation graph).",
            ),
            cli_owned=True,
        ),
    }


def _ensure_initialized_log(path: Path, timestamp: str) -> None:
    existing = path.read_text(encoding="utf-8")
    for line in existing.splitlines():
        fields = line.split(" | ", 4)
        is_initialized = (
            len(fields) == 5
            and fields[0].startswith("- ")
            and fields[1] == "initialized"
        )
        if is_initialized:
            return
    entry = format_log_entry(
        LogEntry(
            at=timestamp,
            action="initialized",
            actor="kb-cli",
            doc_ids=[],
            note="KB scaffolded by kb init",
        )
    )
    separator = "" if not existing or existing.endswith("\n") else "\n"
    with path.open("a", encoding="utf-8", newline="\n") as stream:
        stream.write(f"{separator}{entry}\n")


def init_kb(root: Path, *, force: bool = False) -> InitResult:
    resolved = root.expanduser().resolve()
    resolved.mkdir(parents=True, exist_ok=True)
    timestamp = _utc_now()
    result = InitResult(root=resolved)
    for relative_path, entry in sorted(_manifest(timestamp).items()):
        target = resolved / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        if not target.exists():
            target.write_text(entry.content, encoding="utf-8", newline="\n")
            result.created.append(relative_path)
        elif force and entry.cli_owned:
            target.write_text(entry.content, encoding="utf-8", newline="\n")
            result.overwritten.append(relative_path)
        else:
            result.skipped.append(relative_path)
    _ensure_initialized_log(resolved / "log.md", timestamp)
    return result
