from __future__ import annotations

from pathlib import Path

from kb.core.scan import read_frontmatter

INDEX_COMMENT = "<!-- Generated by kb — do not edit; run `kb index` to regenerate. -->"


def render_index(title: str, description: str, listing: str = "") -> str:
    content = (
        f"---\ntype: index\ndescription: {description}\n---\n"
        f"# {title}\n\n{INDEX_COMMENT}\n"
    )
    return content if not listing else f"{content}\n{listing}\n"


def _frontmatter_closing(lines: list[str]) -> int:
    return next(
        index
        for index, line in enumerate(lines[1:], start=1)
        if line.rstrip("\r\n") == "---"
    )


def _heading(path: Path) -> str:
    lines = path.read_text(encoding="utf-8").splitlines()
    closing = _frontmatter_closing(lines)
    for line in lines[closing + 1 :]:
        if line.startswith("# "):
            return line[2:]
    return path.parent.name


def _description(frontmatter: dict[str, object]) -> str | None:
    value = frontmatter.get("description")
    return value if isinstance(value, str) else None


def render_directory_listing(root: Path, directory: Path) -> str:
    subdirectories: list[str] = []
    files: list[str] = []
    for child in sorted(path for path in directory.iterdir() if path.is_dir()):
        index = child / "index.md"
        if not index.is_file():
            continue
        frontmatter = read_frontmatter(index).root
        tail = (
            f" - {description}"
            if (description := _description(frontmatter))
            else ""
        )
        subdirectories.append(f"* [{_heading(index)}]({child.name}/index.md){tail}")
    for child in sorted(directory.glob("*.md")):
        if child.name in {"index.md", "log.md"}:
            continue
        frontmatter = read_frontmatter(child).root
        if frontmatter.get("type") == "log":
            continue
        doc_id = frontmatter.get("id")
        title = frontmatter.get("title") or child.stem
        if doc_id is None:
            line = f"* [{title}]({child.name})"
        else:
            line = f"* [{doc_id}][{title}]({child.name})"
        if description := _description(frontmatter):
            line += f" - {description}"
        files.append(line)
    sections: list[str] = []
    if subdirectories:
        sections.append("## Subdirectories\n" + "\n".join(subdirectories))
    if files:
        sections.append("## Files\n" + "\n".join(files))
    return "\n\n".join(sections)


def create_directory_index(root: Path, directory: Path) -> str:
    relative = directory.relative_to(root).as_posix()
    return render_index(
        directory.name,
        f"Documents under {relative}/.",
        render_directory_listing(root, directory),
    )


def regenerate_directory_index(root: Path, directory: Path) -> str:
    path = directory / "index.md"
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)
    closing = _frontmatter_closing(lines)
    frontmatter_block = "".join(lines[: closing + 1])
    if not frontmatter_block.endswith("\n"):
        frontmatter_block += "\n"
    body = f"# {_heading(path)}\n\n{INDEX_COMMENT}\n"
    listing = render_directory_listing(root, directory)
    return (
        frontmatter_block + body
        if not listing
        else frontmatter_block + body + f"\n{listing}\n"
    )
