from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path

from pydantic import BaseModel, Field

from kb.core.frontmatter import yaml_scalar
from kb.core.scan import read_frontmatter_bytes

INDEX_COMMENT = "<!-- Generated by kb — do not edit; run `kb index` to regenerate. -->"


class FileListingMetadata(BaseModel):
    filename: str
    doc_id: str | None
    title: str
    description: str | None
    type_name: str | None


class SubdirectoryListingMetadata(BaseModel):
    name: str
    title: str
    description: str | None


class DirectoryListingMetadata(BaseModel):
    files: list[FileListingMetadata] = Field(default_factory=list)
    subdirectories: list[SubdirectoryListingMetadata] = Field(default_factory=list)


def render_index(title: str, description: str, listing: str = "") -> str:
    content = (
        f"---\ntype: index\ndescription: {yaml_scalar(description)}\n---\n"
        f"# {title}\n\n{INDEX_COMMENT}\n"
    )
    return content if not listing else f"{content}\n{listing}\n"


def _frontmatter_closing(lines: list[str]) -> int:
    try:
        return next(
            index
            for index, line in enumerate(lines[1:], start=1)
            if line.rstrip("\r\n") == "---"
        )
    except StopIteration as error:
        raise ValueError("index is missing closing frontmatter delimiter") from error


def _heading_from_text(text: str, fallback: str) -> str:
    lines = text.splitlines()
    closing = _frontmatter_closing(lines)
    for line in lines[closing + 1 :]:
        if line.startswith("# "):
            return line[2:]
    return fallback


def _description(frontmatter: dict[str, object]) -> str | None:
    value = frontmatter.get("description")
    return value if isinstance(value, str) else None


def file_listing_line(
    filename: str,
    doc_id: str | None,
    title: str,
    description: str | None,
) -> str:
    line = (
        f"* [{title}]({filename})"
        if doc_id is None
        else f"* [{doc_id}][{title}]({filename})"
    )
    return line if not description else f"{line} - {description}"


def subdirectory_listing_line(
    name: str,
    description: str | None,
    *,
    title: str | None = None,
) -> str:
    line = f"* [{name if title is None else title}]({name}/index.md)"
    return line if not description else f"{line} - {description}"


def file_listing_metadata(filename: str, content: bytes) -> FileListingMetadata:
    frontmatter = read_frontmatter_bytes(content).root
    doc_id = frontmatter.get("id")
    title = frontmatter.get("title") or Path(filename).stem
    type_name = frontmatter.get("type")
    return FileListingMetadata(
        filename=filename,
        doc_id=str(doc_id) if doc_id is not None else None,
        title=str(title),
        description=_description(frontmatter),
        type_name=type_name if isinstance(type_name, str) else None,
    )


def subdirectory_listing_metadata(
    name: str,
    content: bytes,
) -> SubdirectoryListingMetadata:
    text = content.decode("utf-8", errors="strict")
    frontmatter = read_frontmatter_bytes(content).root
    return SubdirectoryListingMetadata(
        name=name,
        title=_heading_from_text(text, name),
        description=_description(frontmatter),
    )


def render_listing_metadata(
    existing: DirectoryListingMetadata,
    *,
    planned_files: Mapping[str, str] | None = None,
    planned_subdirectories: Mapping[str, str] | None = None,
) -> str:
    subdirectories = {
        item.name: subdirectory_listing_line(
            item.name,
            item.description,
            title=item.title,
        )
        for item in existing.subdirectories
    }
    files = {
        item.filename: file_listing_line(
            item.filename,
            item.doc_id,
            item.title,
            item.description,
        )
        for item in existing.files
        if item.type_name != "log"
        and item.filename not in {"index.md", "log.md"}
    }
    subdirectories.update(planned_subdirectories or {})
    files.update(planned_files or {})
    sections: list[str] = []
    if subdirectories:
        sections.append(
            "## Subdirectories\n"
            + "\n".join(subdirectories[name] for name in sorted(subdirectories))
        )
    if files:
        sections.append("## Files\n" + "\n".join(files[name] for name in sorted(files)))
    return "\n\n".join(sections)


def render_projected_directory_index(
    source: bytes,
    directory_name: str,
    existing: DirectoryListingMetadata,
    *,
    planned_files: Mapping[str, str] | None = None,
    planned_subdirectories: Mapping[str, str] | None = None,
) -> str:
    text = source.decode("utf-8", errors="strict")
    lines = text.splitlines(keepends=True)
    closing = _frontmatter_closing(lines)
    frontmatter_block = "".join(lines[: closing + 1])
    if not frontmatter_block.endswith("\n"):
        frontmatter_block += "\n"
    body = f"# {_heading_from_text(text, directory_name)}\n\n{INDEX_COMMENT}\n"
    listing = render_listing_metadata(
        existing,
        planned_files=planned_files,
        planned_subdirectories=planned_subdirectories,
    )
    return (
        frontmatter_block + body
        if not listing
        else frontmatter_block + body + f"\n{listing}\n"
    )


def _path_listing_metadata(directory: Path) -> DirectoryListingMetadata:
    subdirectories: list[SubdirectoryListingMetadata] = []
    files: list[FileListingMetadata] = []
    for child in sorted(path for path in directory.iterdir() if path.is_dir()):
        index = child / "index.md"
        if not index.is_file():
            continue
        subdirectories.append(
            subdirectory_listing_metadata(child.name, index.read_bytes())
        )
    for child in sorted(directory.glob("*.md")):
        if child.name in {"index.md", "log.md"}:
            continue
        files.append(file_listing_metadata(child.name, child.read_bytes()))
    return DirectoryListingMetadata(
        files=files,
        subdirectories=subdirectories,
    )


def render_directory_listing(
    root: Path,
    directory: Path,
    *,
    planned_files: Mapping[str, str] | None = None,
    planned_subdirectories: Mapping[str, str] | None = None,
) -> str:
    return render_listing_metadata(
        _path_listing_metadata(directory),
        planned_files=planned_files,
        planned_subdirectories=planned_subdirectories,
    )


def create_directory_index(root: Path, directory: Path) -> str:
    relative = directory.relative_to(root).as_posix()
    return render_index(
        directory.name,
        f"Documents under {relative}/.",
        render_directory_listing(root, directory),
    )


def regenerate_directory_index(
    root: Path,
    directory: Path,
    *,
    source: bytes | None = None,
    planned_files: Mapping[str, str] | None = None,
    planned_subdirectories: Mapping[str, str] | None = None,
) -> str:
    path = directory / "index.md"
    index_source = (
        path.read_text(encoding="utf-8").encode("utf-8")
        if source is None
        else source
    )
    return render_projected_directory_index(
        index_source,
        path.parent.name,
        _path_listing_metadata(directory),
        planned_files=planned_files,
        planned_subdirectories=planned_subdirectories,
    )
