from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

import pytest
from typer.testing import CliRunner

from kb.cli.app import app


@pytest.fixture
def runner() -> CliRunner:
    return CliRunner()


@pytest.fixture
def invoke_init(runner: CliRunner, monkeypatch) -> Callable[..., object]:
    def invoke(cwd: Path, *arguments: str):
        monkeypatch.chdir(cwd)
        return runner.invoke(app, ["init", *arguments])

    return invoke


def expected_index(title: str, description: str, listing: str = "") -> str:
    content = (
        f"---\ntype: index\ndescription: {description}\n---\n"
        f"# {title}\n\n"
        "<!-- Generated by kb — do not edit; run `kb index` to regenerate. -->\n"
    )
    return content if not listing else f"{content}\n{listing}\n"


def expected_manifest(timestamp: str) -> dict[str, str]:
    root_listing = """## Subdirectories
* [Governance](governance/index.md) - Project governance — configuration, conventions, and templates.
* [Raw Evidence](raw/index.md) - Immutable evidence — sources, session records, and feedback.
* [Synthetic Documents](synthetic/index.md) - Human-created, agent-maintained documents (the derivation graph)."""
    governance_listing = """## Subdirectories
* [Templates](templates/index.md) - Optional per-type document templates.

## Files
* [GOVERNANCE-CONVENTIONS][Project Conventions](conventions.md) - Standing conventions for this knowledge base. Human-maintained.
* [GOVERNANCE-KB-CONFIG][KB Configuration Reference](kb-config.md) - Explains each field in the root kb-config.json. Human-readable companion to the machine-read config."""
    raw_listing = """## Subdirectories
* [Session Records](chats/index.md) - Session records from kb-author and kb-ingest sessions (immutable).
* [Feedback](feedback/index.md) - Consumer feedback about synthetic documents (immutable).
* [Sources](sources/index.md) - Normalized external evidence (immutable)."""
    return {
        "governance/conventions.md": """---
id: GOVERNANCE-CONVENTIONS
type: conventions
title: Project Conventions
description: Standing conventions for this knowledge base. Human-maintained.
---
# Project Conventions

Standing conventions for this knowledge base. Human-maintained.

## Writing
(none yet)

## Structure
(none yet)
""",
        "governance/index.md": expected_index(
            "Governance",
            "Project governance — configuration, conventions, and templates.",
            governance_listing,
        ),
        "governance/kb-config.md": """---
id: GOVERNANCE-KB-CONFIG
type: kb-config
title: KB Configuration Reference
description: Explains each field in the root kb-config.json. Human-readable companion to the machine-read config.
---
# KB Configuration Reference

The project's configuration and root marker is `kb-config.json` at the KB root.
It is strict JSON, read directly by `kb` commands. Edit the fields below to suit
the project; `schema` is managed by `kb` — do not edit it.

## Fields

- **`schema`** — KB layout schema version. Reserved and tooling-owned; `kb`
  refuses a KB whose schema is newer than the CLI understands.
- **`types`** — document type vocabulary (open list). Examples: `outcome`,
  `ux-flow`, `coding-spec`, `test-plan`, `adr`, `runbook`, `context-package`.
  An empty list means types are not yet constrained.
- **`tags`** — tag vocabulary. `kb validate` flags any document tag not listed
  here. An empty list means no tags are declared.
- **`id_prefixes`** — the id prefix used per document class: `synthetic` (`KB`),
  `source` (`RAW`), `chat` (`CHAT`), `feedback` (`FEED`). Ids are `<PREFIX>-<6+ digits>`.
- **`propagation_auto_safe`** — change classes governance considers auto-safe
  during propagation (CS3). Start empty; expand from field data (PRD OQ1).
""",
        "governance/templates/index.md": expected_index(
            "Templates", "Optional per-type document templates."
        ),
        "index.md": expected_index(
            "Knowledge Base",
            "Root of the knowledge base — raw evidence, synthetic documents, and governance.",
            root_listing,
        ),
        "kb-config.json": """{
  "schema": 1,
  "types": [],
  "tags": [],
  "id_prefixes": {
    "synthetic": "KB",
    "source": "RAW",
    "chat": "CHAT",
    "feedback": "FEED"
  },
  "propagation_auto_safe": []
}
""",
        "log.md": f"""---
type: log
---
<!-- KB history — append-only; written by `kb log`. Format: - <UTC ISO> | <action> | <actor> | <ids or -> | <note> -->
# Knowledge Base Log

- {timestamp} | initialized | kb-cli | - | KB scaffolded by kb init
""",
        "raw/chats/index.md": expected_index(
            "Session Records",
            "Session records from kb-author and kb-ingest sessions (immutable).",
        ),
        "raw/feedback/index.md": expected_index(
            "Feedback", "Consumer feedback about synthetic documents (immutable)."
        ),
        "raw/index.md": expected_index(
            "Raw Evidence",
            "Immutable evidence — sources, session records, and feedback.",
            raw_listing,
        ),
        "raw/sources/index.md": expected_index(
            "Sources", "Normalized external evidence (immutable)."
        ),
        "synthetic/index.md": expected_index(
            "Synthetic Documents",
            "Human-created, agent-maintained documents (the derivation graph).",
        ),
    }
